In [3]:
from datetime import date

d0 = date(2000, 3, 29)
d1 = date(2024, 4, 1)

years = d1.year - d0.year
months = d1.month - d0.month
days = d1.day - d0.day

if days < 0:
    months -= 1
    days += (d1.replace(year=d1.year, month=d1.month-1) - d1.replace(year=d1.year, month=d1.month-2)).days

if months < 8:
    years -= 1
    months += 12

print(f"Years: {years}, Months: {months}, Days: {days}")


Years: 23, Months: 12, Days: 1


In [10]:
from datetime import datetime

def calculate_age(birth_date):
    today = datetime.today()
    age_in_years = today.year - birth_date.year
    age_in_months = today.month - birth_date.month
    age_in_days = today.day - birth_date.day

    if age_in_days < 0:
        age_in_months -= 1


    if age_in_months < 0:
        age_in_years -= 1
        age_in_months += 12

    total_days = (today - birth_date).days
    total_hours = total_days * 24
    total_minutes = total_hours * 60
    total_seconds = total_minutes * 60

    return age_in_years, age_in_months, age_in_days, total_days, total_hours, total_minutes, total_seconds

birth_date_input = input("Enter your birthdate (YYYY-MM-DD): ").replace(" ", "")
birth_date = datetime.strptime(birth_date_input, "%Y-%m-%d")

years, months, days, total_days, hours, minutes, seconds = calculate_age(birth_date)

print(f"Age: {years} years, {months} months, {days} days")
print(f"Total days: {total_days}")
print(f"Total hours: {hours}")
print(f"Total minutes: {minutes}")
print(f"Total seconds: {seconds}")



Enter your birthdate (YYYY-MM-DD): 2000-03-29
Age: 24 years, 8 months, -25 days
Total days: 9016
Total hours: 216384
Total minutes: 12983040
Total seconds: 778982400


In [11]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

print(np.vstack((a, b)))
print(np.hstack((a, b)))


[[1 2]
 [3 4]]
[1 2 3 4]


In [13]:
import numpy as np

array1d = np.array([1, 2, 3])
print(array1d)

array2d = np.array([[1, 2], [3, 4]])
print(array2d)


[1 2 3]
[[1 2]
 [3 4]]


In [14]:
import numpy as np

zeros_array = np.zeros((2, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
import numpy as np

array = np.array([10, 20, 30, 40])
print(array[1])

array2d = np.array([[1, 2], [3, 4]])
print(array2d[1, 1])


20
4


In [16]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])
print(array[1:4])


[20 30 40]


In [17]:
import numpy as np

array2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array2d[:, 1])


[2 5]


In [18]:
import numpy as np

array = np.array([10, 20, 30, 40])
print(array[array > 20])


[30 40]


In [19]:
import numpy as np

array = np.arange(6)
reshaped = array.reshape(2, 3)
print(reshaped)


[[0 1 2]
 [3 4 5]]


In [20]:
import numpy as np

array = np.arange(6).reshape(2, 3)
print(np.hsplit(array, 3))


[array([[0],
       [3]]), array([[1],
       [4]]), array([[2],
       [5]])]
